[build]
  publish = "docs"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://sage-dragon-a030ca.netlify.app/*"
  to   = "https://designer.gorillaprintshop.com/:splat"
  status = 301
  force = true
